### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by cmcnamara87** [cmcnamara87/progress#40]
- [ ] fix styling for mobile view @cruion
- [ ] embedding twitch streams  @cruion
- [ ] better embedding
- [ ] work out why comments are broken on project pages
- [ ] refine post parser / embedder in angular (fork project)
- [ ] sharing a link to a post 
- [ ] search
- [ ] user search
- [ ] project search
- [ ] post search?
- [ ] tags on posts
- [ ] filter posts by tags
- [ ] edit already submitted posts
- [ ] change image upload to be similar to how github does it, embeds the uploaded image url into the post text box
- [ ] kill the leadeboard
- [ ] get the times working on a users page
- [ ] get the times working on a project page
- [ ] add some kind of dashboard to the users page with all their times or something (weekly?)
- [ ] add editing user profile
- [ ] add uploading user profile picture
- [ ] add ability to link to twitter/facebook/dribbble/behance etc on a profile page
- [ ] add private projects
- [ ] switch design to follow projects, not people
- [ ] let people know, when someone whose project they follow, adds a new project (ugh)
- [ ] add multi-image posts
- [x] Expand Landing page #9  @nickgeorgiou 
- [x] Add more info to registration page
- [ ] add follow/unfollow resource
- [ ] Add 'follow' page that appears post registration
- [x] Improve onboarding workflow, landing -> register -> follow -> feed
- [ ] add following / unfollowing button functionality
- [ ] create users page
- [x] create project page
- [x] retire diary page, and swap with project page
- [ ] add invite backend
- [ ] add invite UI to feed page
- [x] add notification emails
- [ ] add daily/weekly digest emails
- [ ] add graphs of weekly progress per project
- [ ] add user graphs
- [ ] add progress emails (contain stats not about user stuff)
- [ ] add notifications in desktop app
- [x] fix up new proejct url in desktop app
- [x] fix up clicking notification url in desktop app
- [ ] infinite scrolling on feed back
- [ ] infinite scrolling on project page
